version: '3.9'
services:
    app:
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .env:/app/.env
        command: npm start
        logging:
            driver: "json-file"
            options:
                max-size: "1m"

